apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weather-api
  template:
    metadata:
      labels:
        app: weather-api
    spec:
      containers:
        - image: anzeha/weather-api
          name: weather-api
          env:
            - name: APPPROPERTIES_WEATHERAPI_ACCESSKEY
              valueFrom:
                secretKeyRef:
                  name: pg-pass
                  key: APPPROPERTIES_WEATHERAPI_ACCESSKEY
          ports:
            - containerPort: 8086
              name: server
              protocol: TCP
         

---

apiVersion: v1
kind: Service
metadata:
  name: weather-api
spec:
  type: ClusterIP
  ports:
    - port: 8086
      protocol: TCP
      targetPort: server
  selector:
    app: weather-api
