name: build with Maven and package as Docker image

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set vars
        id: vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

      - name: Get Time
        id: time
        uses: nanzm/get-time-action@v1.0
        with:
          timeZone: 1
          format: 'YYYY-MM-DD-HH-mm-ss'

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          file: ./Dockerfile_with_maven_build
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/weather-api:${{ steps.vars.outputs.sha_short }}
      - name: Setup AKS context
        uses: azure/aks-set-context@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          resource-group: ${{ secrets.AZURE_RESOURCE_GROUP }}
          cluster-name: rso-skupina3
      - name: deploy to kubernetes
        uses: Azure/k8s-deploy@v1.4
        with:
          manifests: |
            k8s/weather-api-deployment.yaml
          images: |
            ${{ secrets.DOCKERHUB_USERNAME }}/weather-api:${{ steps.vars.outputs.sha_short }}
